### ISSUE TITLE
License Missing from Files

### ISSUE THREAD

**Issue by nynymike** [GSLabDev/OTPManager#1]
Hi guys. Thanks for open sourcing this code. We are just about to add OTP features to the Gluu Server, and would like to consider it. It's best practice to include the license in all artifacts. This makes it super clear... just providing one license in the root folder is not quite as clear. Perhaps you would consider making this change.

**Comment by GSLabDev** [comment]
Thanks Mike. We have updated all artifacts to include the license, as suggested.

Please feel free to write to us at [osc-otplibrary@gslab.com] for any assistance during the integration with Gluu server.

Regards,
OTP Library team @ GS Lab.
